name: tecnigo_app
description: Servicios técnicos a domicilio (Flutter + Supabase)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Backend
  supabase_flutter: ^2.8.0

  # State / routing
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0

  # Env
  flutter_dotenv: ^5.1.0

  # Maps + geolocalización
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  http: ^1.2.2

  # UI extras
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env